apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: production
  LOG_LEVEL: info
  PORT: "3000"
  SERVICE_NAME: backend

  POSTGRES_HOST: postgres-rw
  POSTGRES_PORT: "5432"

  DB_CONNECT_MAX_RETRIES: "30"
  DB_CONNECT_RETRY_DELAY_MS: "2000"
