apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres-cluster.yaml
- backend-configmap.yaml
- backend-service.yaml
- backend-deployment.yaml
- frontend-configmap.yaml
- frontend-service.yaml
- frontend-deployment.yaml
- ingress.yaml

configMapGenerator:
- files:
  - initdb/01_schema.sql
  - initdb/02_seed.sql
  - initdb/03_ownership.sql
  name: postgres-initdb

generatorOptions:
  disableNameSuffixHash: true

labels:
- pairs:
    app.kubernetes.io/part-of: practice

images:
- name: practice-backend
  newName: 213851292053.dkr.ecr.us-east-1.amazonaws.com/practice-backend
  newTag: a263c2b
- name: practice-frontend
  newName: 213851292053.dkr.ecr.us-east-1.amazonaws.com/practice-frontend
  newTag: a263c2b
